"use client";
import React from 'react';
import Image from "next/image";


type dounutlabelItemType={
    text:string,
    font:{
        size:number
    }
}

type dounutType={
    labels:dounutlabelItemType[]
}

type dataSetType={
    label:string,
    data:number[],
    fill:boolean,
    borderColor:string
}
type dataType={
    type:string,
    data:{
        labels:string[],
        datasets:dataSetType[] | null | undefined,
    },
    options?:{
        plugins:{
            doughnutLabel:{
                labels:dounutType
            }
        }
    }
}
const GenerateChart = ({graphData,summary,name}:{graphData:dataType | null,summary:string,name:string}) => {
    const url="https://quickchart.io/chart";

  return (
    <div className="lg:mx-auto lg:container bg-white rounded-lg p-2">
        <div className="lg:mx-auto lg:container my-auto flex flex-col justify-center items-start px-2">
        <h3 className="text-2xl m-auto text-center font-bold text-black" style={{color:"black"}}>Summary</h3>
        <p className="text-md m-auto w-full px-2 lg:w-3/4 lg:px-0  " style={{color:"black"}}>{summary}</p>
        <img src={`${url}?c=${JSON.stringify(graphData)}`}
         alt={`www.masterconnect.ca`}
        //  fill={true}
         className="aspect-video content-fit"
        />
        <small className="font-bold text-blue"><span style={{color:"black"}}>presented by: </span>{name}</small>
        <small className="font-bold text-blue"><span style={{color:"black"}}>generated by by: </span>www.masterconnect.ca<span style={{color:"black"}}> @ masterultils.ca</span></small>
        </div>
    </div>
  )
}

export default GenerateChart